---
title: "DT2"
author: "Leo Feng"
date: "2021/9/1"
output: html_document
---
```{r}
rm(list=ls())
library(randomForest)
library(tidyverse)

### ALL URLs need to be updated ###
### link to seoul_bike_agg_mean_FG_new.csv : https://github.com/Jiian/seoulbike/blob/main/feature_engineering/seoul_bike_agg_mean_FG_new.csv  ###
### link to 7days_demo_FG.csv : https://github.com/Jiian/seoulbike/blob/main/data/7days_demo_FG.csv  ###

auto_URL = 'https://raw.githubusercontent.com/Jiian/seoulbike/main/feature_engineering/seoul_bike_agg_mean_FG_new.csv?token=AVLOXCIPP7GV5E5GR6IZ5M3BHMX3G'

#auto<-read.csv("seoulbike/feature_engineering/seoul_bike_agg_mean_FG_new.csv")

demo_URL = 'https://raw.githubusercontent.com/Jiian/seoulbike/main/data/7days_demo_FG.csv?token=AVLOXCLERTILKVGOFV4JX2LBHMX4E'

#demo<-read.csv("seoulbike/data/7days_demo_FG.csv")

auto<-read.csv(auto_URL)
demo<-read.csv(demo_URL)
```

```{r}
getDT<-function(x,title=""){
  set.seed(12)
  select<-sample(1:nrow(x),length(x$rent_count)*0.8)
  train=x[select,]
  test=x[-select,]
  train.forest<-randomForest(rent_count~.,data=train,importance=TRUE, ntree=100)
  pred<-predict(train.forest,test)
  MPE<-mean(abs((test$rent_count-pred)/test$rent_count))
  
  plot(test$rent_count, pred, main = title,
    xlab = 'rent_count', ylab = 'Predict')
  abline(1, 1)
  
  print(train.forest)
  print(train%>%select(-rent_count)%>%colnames())#features names
  print(paste("Mean of absolute percentage error:",MPE))
  list(train.forest,train)
}

DT<-getDT(auto,title="all features")

```

```{r}
#Cross validation
#perform 5 times with 10 folds
train<-DT[[2]]
Train.cv <- replicate(5,rfcv(train[-ncol(train)], train$rent_count, cv.fold = 10, step=1.5),simplify = FALSE)

#Table and Plot 
#No. features VS cross validation errors 
train.cv <- data.frame(sapply(Train.cv, '[[', "error.cv"))
train.cv$features <- rownames(train.cv)
train.cv <- gather(train.cv,key="key",value="value",-features)
train.cv$features <- as.numeric(as.character(train.cv$features))
 
train.cv.mean <- aggregate(train.cv$value, by = list(train.cv$features), FUN = mean)
head(train.cv.mean, 15)#lowest x when 5 features

library(ggplot2)
 
ggplot(train.cv.mean, aes(Group.1, x)) +
geom_line() +
theme(panel.grid = element_blank(), panel.background = element_rect(color = 'black', fill = 'transparent')) +
labs(title = '',x = 'Number of Features', y = 'Cross-validation error')
```
```{r}
#Plot of variable importance
#2 standards: Increasing of MSE and Increasing node purity
varImpPlot(DT[[1]], n.var = 10,
    main = 'Top 10 - variable importance',
    cex=0.7)
```
```{r}
# extracts two sets each contains 5 features corresponding to the top 5 increasing MSE and increasing node purity
# perform randomForest on each set
important_features<-data.frame(importance(DT[[1]]), check.names = FALSE)

features_MSE <- important_features[order(important_features$"%IncMSE", decreasing = TRUE), ][c(1:5),]%>%rownames()
DTMSE<-getDT(auto%>%select(c(rent_count,features_MSE)),title="top5 incMSE")

features_purity <- important_features[order(important_features$IncNodePurity, decreasing = TRUE), ][c(1:5),]%>%rownames()
DTpurity<-getDT(auto%>%select(c(rent_count,features_purity)),title="top5 incnodepurity")

```
```{r}
# compare two versions of predicted rent count and pick the better one
demo_predMSE<-predict(DTMSE[[1]],demo)
demo_predpurity<-predict(DTpurity[[1]],demo)
mean(abs((demo$rent_count-demo_predMSE)/demo$rent_count))
mean(abs((demo$rent_count-demo_predpurity)/demo$rent_count))
demo_predpurity# predicted rent count for 7days demo
demo$predicted_rent_count=demo_predpurity
```



