---
title: "PCA Bike"
author: "ch"
date: "8/27/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Loading libraries and csv

```{r}
library(tidyverse)
bike <- readRDS("../data/bike_clean.rds")
```

# 1 Further Cleaninng of Bike Data
# 1.1 Aggregating bike data
```{r}
bike <- bike %>%
  filter(.$open == "Yes")

conti <- bike %>%
  group_by(date) %>%
  summarise(rent_count = sum(rent_count),
            temperature = median(temperature),
            rainfall = sum(rainfall),
            snowfall = sum(snowfall),
            wind_speed= median(wind_speed),
            visibility = median(visibility),
            solar_radiation = median(solar_radiation),
            dewpoint_temp = median(dewpoint_temp),
            humidity = median(humidity))

mode_season <- bike %>%
  group_by(date) %>%
  count(date, season) %>%
  slice(which.max(n)) %>%
  select(-3)

mode_hol <- bike %>%
  group_by(date) %>%
  count(date, holiday) %>%
  slice(which.max(n)) %>%
  select(-3)

bike_agg <- inner_join(conti, mode_season, by= "date") %>%
  inner_join(mode_hol, by= "date") %>%
  mutate(season = as.factor(season),
         holiday = as.factor(holiday))

glimpse(bike_agg) 
head(bike_agg)
```

# 1.2 Adding New Column 
```{r}
bike_agg_with_season_no <- bike_agg%>%
  mutate(season_no = case_when(
  .$season == "Winter" ~ 4,
  .$season == "Spring" ~ 1,
  .$season == "Autumn" ~ 3,
  .$season == "Summer" ~ 2
))
# As PCA is a unsupervised learning algorithm, we will drop the season column
nrow(bike_agg_with_season_no)
write.csv(bike_agg_with_season_no, "bike_agg_with_season_no.csv")
saveRDS(bike_agg_with_season_no,"bike_agg_with_season_no.rds")
```



